// Total number of quiz items (pairs)
const TOTAL_QUIZZES = 5; // update as you add more

const imageElement = document.getElementById("quiz-image");
const descriptionElement = document.getElementById("description");
const revealBtn = document.getElementById("reveal-btn");
const nextBtn = document.getElementById("next-btn");

let currentQuiz = null;

// Descriptions shared by each image pair
const descriptions = {
    1: `Fires on the Rise in the Far North - In the far north, wildfires are breaking old patterns. Satellite data show that wildland fires once scattered across the Arctic are now surging in numbers—particularly in northern Eurasia—and many are burning more intensely than before.
These maps show the number of fires detected by the MODIS (Moderate Resolution Imaging Spectroradiometer) sensors on NASA’s Aqua and Terra satellites. The map on the left shows fire detections from 2002 to 2012 (yellow), while the map on the right shows detections from 2012 to 2024 (orange). The largest circles indicate areas with 15,000 or more detected fires, while the smallest circles represent areas with 1,000 or fewer. Fire detection data are from NASA’s Fire Information for Resource Management System (FIRMS).
Although the geographical distribution of high-latitude wildfires varies from year to year, the maps reveal some clear long-term patterns. In the 2000s, fires north of 60 degrees latitude appeared across both North America and Eurasia, but starting in the early 2010s, their numbers skyrocketed, most dramatically in Eurasia. Even the icy island of Greenland entered a new fire regime during this period, experiencing more large fires, though still too few to be visible on these maps.
Researchers attribute these trends to rising temperatures, which have made northern landscapes more flammable, along with a poleward expansion of lightning—the primary ignition source for these fires. The findings are detailed in a report published in 2025 by the Arctic Monitoring and Assessment Programme (AMAP), a working group of the Arctic Council.
The number of fire detections and their distribution, however, is just one metric of the Arctic’s changing fire regime. According to NASA researchers, fires in this region are also burning larger, hotter, and longer than they did in previous decades.`,

    2: `Fire Threatens Rare Forests in Argentina - Summer is usually peak tourism season in Argentina’s Chubut province, a time when hikers and sightseers arrive to explore glacial lakes and cirques, alpine valleys, and towering forests. In January 2026, however, some visitors to the remote Patagonian region instead found themselves fleeing raging wildland fires.
On January 8, 2026, the MODIS (Moderate Resolution Imaging Spectroradiometer) on NASA’s Aqua satellite captured this image of smoke billowing from two large fires burning in and around Los Alerces National Park, a UNESCO World Heritage site. NASA satellites began detecting widespread fire activity in the area on January 6.
The more southerly blaze was spreading east on ridges between Lago Rivadavia, Lago Futalaufquen, and Lago Menéndez; the more northerly fire was burning on steep hillsides around Lago Epuyén. All of the lakes occupy U-shaped glacial troughs, valleys with unusually flat bases and steep sides carved by glacial and periglacial erosion. Satellite-based estimates from the Global Wildfire Information System indicate that fires charred more than 175 square kilometers (67 square miles) across Patagonia between January 5 and 8.
The ridges are blanketed with temperate Patagonian Andean forest, including sections of Valdivian rainforest, with rare stands of alerce (Fitzroya cupressoides). A type of cypress, these huge, slow-growing conifers are the second-longest-lived trees on Earth, with some surviving for more than 3,600 years. According to UNESCO documents, Los Alerces National Park protects 36 percent of Argentina’s alerce forests, including stands with the greatest genetic variability on the eastern slopes of the Andes. The park’s forests also contain exclusive genetic variants and the oldest individuals in the country.
News outlets and the national park reported challenging weather conditions for firefighters on the ground, who faced high temperatures, low humidity, and strong winds in recent days. Standardized Precipitation Index data from the National Integrated Drought Information System show that unusually dry conditions over the past several months have likely primed vegetation to burn. News outlets reported that at least 3,000 tourists had to be evacuated from a lake resort near Lago Epuyén.`,

    3: `Ganges Delta Under a Winter Shroud of Fog - Winter weather took hold across the Indo-Gangetic Plain in early January 2026, bringing dense fog and cold temperatures to much of the flat, fertile lands that span from Pakistan and northern India to Bangladesh.
This image shows low-lying clouds over the delta on the morning of January 6, captured by the MODIS (Moderate Resolution Imaging Spectroradiometer) on NASA’s Terra satellite. Dense fog, particularly radiation fog, is common this time of year, forming when ground temperatures are cool, winds are light, and moisture is abundant near the surface. The meteorological departments of both Bangladesh and India called for moderate to very dense fog over the region that day amid an ongoing cold wave.
Other relatively low-level clouds extend from the land areas and over the Bay of Bengal. These long, parallel bands of clouds, known as cloud streets, can form when cold air passes over warmer open water, gaining heat and moisture. Rising thermals ascend until they reach a temperature inversion that acts like a lid, forcing the air to roll into long, parallel rotating cylinders. Clouds develop where the air rises, while clear skies appear where the air sinks.
While it appears scenic from above, foggy conditions can pose hazards and snarl daily life for people on the ground. For instance, dense fog early in the month caused major disruptions at the international airport in Dhaka, according to local news reports. Similar disruptions, along with travel delays on roads and railways, were reported in parts of northern, central, and eastern India.`,

    4: `Meltwater Turns Iceberg A-23A Blue - The year that iceberg A-23A first broke away from Antarctica's Filchner Ice Shelf, Ronald Reagan was president of the United States, and the movie Top Gun was setting box office records. Forty years later, the massive tabular berg—one of the largest and longest-lived bergs ever tracked by scientists—is sopping with blue meltwater and on the verge of complete disintegration as it drifts in the South Atlantic between the eastern tip of South America and South Georgia island.
When it first detached from Antarctica in 1986, the berg was nearly twice the size of Rhode Island—about 4,000 square kilometers. Estimates from the U.S. National Ice Center put the berg's area at 1,182 square kilometers (456 square miles) in early January 2026, following the breakup of several sizable pieces in July, August, and September of 2025 as it moved into relatively warm summer conditions by December.
The MODIS image suggests that the ailing iceberg has also sprung a leak. The white area to its left may be the result of what scientists described as a "blowout."`,

    5: `Plants and Algae Swirl Across a South African Reservoir - On clear days in Hartbeespoort, South Africa, satellite images often reveal a reservoir with shades of deep blue interrupted by drifting patches of vivid green. Over the years, these shifting features have included algae blooms—which can affect water quality, ecosystems, and nearby human communities.
In this animation, from June 2022 to July 2023, aquatic plants proliferate, move around the reservoir, and then fade. The animation is composed of images from Harmonized Landsat and Sentinel-2 (HLS), a NASA product that combines imagery from the NASA/USGS Landsat 8 and Landsat 9 satellites and the European Space Agency’s Sentinel-2A, 2B, and 2C satellites.
The green masses can also contain varying amounts of algae, an umbrella term for photosynthetic organisms that live in water, encompassing everything from single-celled cyanobacteria to seaweed. They play a vital role in maintaining healthy ecosystems.`

    6: `Reaching the Precipice in Angola - In southwestern Angola, an expanse of coastal plains comes to an abrupt end at a natural barrier. The Huíla plateau soars above the lowlands to elevations of around 2,300 meters (7,500 feet). The sharp transition results in dramatic landscapes and a sudden change from an arid environment to more-temperate climes.  
The serrated edge of the Huíla plateau zigzags through this image, which is a mosaic of scenes acquired on June 19 and 20, 2025, with the OLI-2 (Operational Land Imager-2) and OLI on the Landsat 9 and Landsat 8 satellites, respectively. Areas around the plateau’s edges appear green with vegetation. But the landscape tends to look much browner by late September, at the end of the region’s dry season, during which almost no rain falls.  

This topography is part of the Great Escarpment of southern Africa, a 5,000-kilometer-long feature running roughly parallel to the continent’s edge. From Angola, it extends south through Namibia, across South Africa, and then northeast into Zimbabwe and Mozambique. The image below, acquired with the VIIRS (Visible Infrared Imaging Radiometer Suite) on the Suomi NPP satellite, shows a longer segment of the escarpment in Angola. Scientists believe the escarpment formed after the breakup of the supercontinent Gondwana in the Jurassic period. Since then, erosion has worn away at the continental margin such that the escarpment now sits 50 to 200 kilometers (30 to 120 miles) back from the coast.  

This Angolan section of the escarpment features dizzying, yet beautiful, landscapes. Tundavala Gap, a gouge eroded into the cliff line, is one of the most iconic with its well-framed view of the plains below. The precipice also presents a substantial obstacle to transportation. A stretch of the Namibe-Lubango Road overcomes this challenge with a series of scenic hairpin turns climbing to Serra da Leba pass near the town of Leba.`,

    7: `An Amphitheater of Rock at Cedar Breaks - When people stand at the rim of the amphitheater in Utah's Cedar Breaks National Monument and look down on an otherworldly landscape of multicolored rock spires, pinnacles, and other geologic oddities, they're looking across tens of millions of years of Earth's history. The same can be said when viewing the bowl-shaped escarpment from space.
The OLI-2 (Operational Land Imager-2) on Landsat 9 captured this view of the amphitheater's semicircular rim and deeply eroded drainages on June 18, 2025. The erosive power of water from Ashdown Creek and several tributaries, along with relentless physical and chemical weathering, is evident in the many channels, cliffs, and canyons that radiate outward from the rim and define the escarpment and amphitheater.

The feature's striking rock formations are composed of sedimentary rock layers laid down roughly 50 to 25 million years ago within a basin that, at times, held a large body of water called Lake Claron. Many of the amphitheater's limestone layers began as sediments that settled on its lakebed as carbonate-rich muds.

Differences in rock type and color, evident in the layering seen in ground photographs and to a degree in Landsat images, reflect differences in environmental conditions during deposition. Lake Claron, for instance, was sometimes quite deep, but during dry periods it was shallow or nonexistent. In wet conditions, iron in muddy sediments was scarce or had too little exposure to oxygen to oxidize, or rust, leaving the resulting rock white or gray. During drier periods, iron in sediments had greater exposure to oxygen, forming minerals that turned layers red and orange. 

After deposition, slow-moving tectonic forces lifted all these rock layers upward, ultimately putting them at the top of the Grand Staircase—an immense sedimentary sequence that stretches south from Cedar Breaks and Bryce Canyon, through Grand Staircase-Escalante National Monument and Zion Canyon, and finally into the Grand Canyon. Younger rock layers are found at the top of the sequence and older layers at the bottom.

The rim at Cedar Breaks, the top of the staircase, sits about 10,000 feet (3,000 meters) above sea level, roughly 7,000 feet above the Colorado River in the Grand Canyon. The high elevation influences everything from the weather to the plants and animals that live there. Winters are long, cold, and snowy, with nearby Brian Head seeing 30 feet (10 meters) of snowfall each year on average.

While the cool temperatures and short growing season are an impediment to many types of vegetation, the slow-growing and notoriously long-lived bristlecone pines found along the escarpment's rim use the harsh conditions to their advantage. Slow growth makes their wood unusually dense, which protects the trees from disease and insects. Likewise, their ability to survive in thin soils, on mostly barren limestone outcrops where little else can grow, protects them from wildfires. Some of the oldest bristlecones in the monument are more than 1,700 years old.

Sitting atop the sedimentary layers, signs of a more volcanically active period also appear in the image. The dark basaltic lava flows visible to the east of the amphitheater formed between 5 million and 10,000 years ago, when several volcanoes on the Markagunt Plateau erupted regularly. Areas of soft, gray rock around the summit of Brian Head—now the site of a ski resort—formed when pyroclastic flows left deposits of tuff strewn across the landscape.`

   8: `Lake Eyre Blushes - The year 2025 was extraordinary for Lake Eyre (also called Kati Thanda-Lake Eyre) in South Australia. Water started flowing into the often-dry, salty plain at the continent’s lowest point in early May after torrential rains in Queensland flooded several rivers that drain toward it. The lake continued to fill in the ensuing months, reaching levels rarely seen.
The lake turned a corner in early October, spring in Australia. Tributaries feeding the basin slowed to a trickle, and evaporation started outpacing inflow from rivers, according to local observers. By the start of December, the Lake Eyre Yacht Club reported that the rivers had dried up, temperatures had warmed with the arrival of summer, and lake levels were dropping rapidly.

As it dried, Lake Eyre displayed more striking changes visible to satellites. The OLI (Operational Land Imager) on Landsat 8 acquired this natural-color image of Lake Eyre on December 15, 2025. The two deepest parts of the lake—Belt Bay and Madigan Gulf—still contained some water, which took on greenish and reddish hues, respectively. (From closer vantage points, Madigan Gulf can appear pink and even orange.)

As Lake Eyre evaporates, the remaining water becomes increasingly saline. Halophilic, or salt-loving, microorganisms thrive in these waters, enough to alter its color over large areas. Direct water samples are needed to identify what microbes are present. Past analyses have detected Dunaliella salina algae in samples, and studies of different pink-colored lakes have found the same algae, along with populations of other halophilic bacteria and archaea. Many of these species are known to produce pigmented compounds such as carotenoids that are colored pink, orange, or red.

Salt-loving algae and bacteria are sensitive to salinity levels and other environmental factors. Different conditions in Belt Bay and Madigan Gulf may support different microbial mixes, accounting for their contrasting colors. A similar-looking contrast between greenish and reddish waters sometimes occurs in Utah’s Great Salt Lake, where a causeway prevents water in the lake’s north and south arms from mixing. Varied salinity, water depth, and microbe populations also affect water color in San Francisco Bay-area salt ponds.

Just how long water will remain in Lake Eyre will depend largely on summer heat and evaporation rates. As an endorheic lake, it has no outflow, and this part of the outback receives very little rain. After complete fills of the lake, for example in 1950, 1974, and 1984, it took up to two years to dry out again.`;


9: `The Galaxy Next Door - From the International Space Station, astronauts gaze upon a vast sea of stars, the view almost entirely unencumbered by Earth’s atmosphere. Their perspective on outer space, as it turns out, extends beyond the Milky Way.

Located about 160,000 light-years away, the Large Magellanic Cloud (LMC) is an irregular dwarf galaxy consisting of billions of stars. It appears as a bright smudge in this photo, which was taken by an astronaut aboard the station on November 28, 2025. Arcing across the bottom of the image is Earth’s limb, along with yellow, green, and diffuse red layers of airglow.

Skywatchers on Earth can also see this nearby galaxy from the Southern Hemisphere and from low Northern Hemisphere latitudes without optical aid. It is part of our Local Group, a galactic neighborhood about 10 million light-years across containing the Milky Way, Andromeda, and Triangulum galaxies, plus around 50 dwarf galaxies, including the LMC.

Although this parcel of space is visible with little or no technology, sophisticated instruments developed by NASA and others have captured extraordinary views of the LMC. Images from the Hubble Space Telescope, the Spitzer Space Telescope, and a combination of missions show its stars and nebulae in different wavelengths.

The LMC is a hotbed of star formation, giving astronomers excellent opportunities to study the life cycle of stars and space dust. A supernova in 1987—the nearest observed in hundreds of years—offered a close-up look at the death of a star and its aftermath. The powerful explosion blazed with the power of 100 million Suns for several months, and scientists observed a bright ring of gas around the exploded star for decades.

More recently, astronomers studied how vast quantities of dust were being forged in the supernova’s glowing remains. A portion of the material may be the source of astronomical new beginnings as building blocks for stars and planets.`;


10: `A Siberian Snowman in Billings - Icons of winter are sometimes found in unexpected places. In one striking example, a series of oval lagoons in a remote part of Siberia forms the shape of a towering snowman when viewed from above. This image, centered on the remote village of Billings and nearby Cape Billings on Russia's Chukchi Peninsula, was captured by the OLI (Operational Land Imager) aboard Landsat 8 on June 16, 2025. Established in the 1930s as a port and supply point for the Soviet Union, the village sits on a narrow sandspit that separates the Arctic Ocean from a series of connected coastal inshore lagoons. The elongated, oval lagoons are frozen over and flanked by sea ice. Though June is one of the warmest months in Billings, ice cover is routine even then. Mean daily minimum temperatures are just minus 0.6 degrees Celsius (30.9 degrees Fahrenheit) in June, according to meteorological data.  

Though the shape may seem engineered, it is natural and the product of geological processes common in the far north. The ground in this part of Siberia is frozen most of the year and pockmarked with spear-shaped ice wedges buried under the surface. Summer melting causes overlying soil to slump, leaving shallow depressions that fill with meltwater and form thermokarst lakes. Once created, consistency in the direction of the winds and waves likely aligned and elongated the lakes into the shapes seen in the image. The thin ridges separating the lakes may represent the edges of different ice wedges below the surface.  

The first reference to humans building snowmen dates back to the Middle Ages, according to the book The History of the Snowman. While three spherical segments are the most common form, other variants dominate in certain areas. In Japan, snowmen typically have just two segments and are rarely given arms. This five-segmented snowman-shaped series of lakes spans about 22 kilometers (14 miles) from top to bottom, making it roughly 600 times longer than the actual snowwoman that held the Guinness record for being the world's tallest snowperson in 2025.  

Snowmen are not the only winter icons tied to this remote landscape. For early expeditions to the Russian Arctic, reindeer offered one of the most reliable modes of transportation. That includes expeditions by the town’s namesake, Commodore Joseph Billings, a British-born naval officer who enlisted in the Russian navy and led a surveying expedition to find a Northeast Passage between 1790 and 1794. Although the hundred-plus members of the expedition did not reach Cape Billings, they explored much of the Chukchi Peninsula, producing some of the first accurate maps and further confirming that Asia and North America were separated by a strait. In the winter months, when their ships were beset with ice, the explorers moved to temporary camps on land and instead surveyed the region with reindeer-drawn wooden sleds, according to historical accounts.  

Indigenous Chukchi people living on the peninsula at the time routinely used reindeer to haul both people and cargo. A pair of reindeer can comfortably haul hundreds of pounds for several hours a day. In addition to their impressive endurance in cold temperatures, reindeer largely feed themselves by digging through snow and grazing on lichens, something that neither sled dogs nor horses can do. Historical documents indicate that the Billings expedition enlisted Chukchi people to manage and care for the reindeer they used, with some accounts suggesting that the explorers used dozens of reindeer at times. While reindeer were mainly used to haul sleds, Chukchi people likely rode them as well. Non-Chukchi members of the expedition reportedly experimented with riding reindeer, though their experiments did not always go smoothly. Billings' secretary and translator Martin Sauer reported using a saddle without stirrups or a bridle and falling 'nearly 20 times' after about three hours of travel in his account of the expedition. Not only that, he added, but the saddle 'at first, causes astonishing pain to the thighs.`;


11: `A Subtle Return of La Niña - After a several-month hiatus, La Niña returned to the equatorial Pacific Ocean in September 2025 and has continued into December. However, this occurrence of El Niño’s cooler counterpart is relatively weak, and its influence on weather and climate over the next several months remains to be seen. Part of the El Niño-Southern Oscillation (ENSO) cycle, La Niña develops when strengthened easterly trade winds intensify the upwelling of cold, deep water in the eastern tropical Pacific. This process cools large swaths of the eastern and central equatorial Pacific while simultaneously pushing warm surface waters westward toward Asia and Australia. In a report published on December 11, the NOAA Climate Prediction Center confirmed that below-average sea surface temperatures associated with La Niña conditions were present and likely to continue for another month or two.  

The shifting wind patterns and the movement of heat within the ocean have a direct impact on sea level. Because cooler water is denser and occupies less volume than warm water, sea levels in the central and eastern Pacific drop during La Niña events. The map above shows sea surface height observed on December 1, 2025. Shades of blue indicate below-normal sea levels, shades of red show above-normal levels, and white represents near-normal conditions. Data for the map were acquired by the Sentinel-6 Michael Freilich satellite and processed by scientists at NASA’s Jet Propulsion Laboratory (JPL). Signals related to seasonal cycles and long-term trends have been removed to highlight sea level changes associated with ENSO and other short-term natural phenomena. The satellite’s twin successor, Sentinel-6B, launched in November 2025 and is expected to begin contributing to ENSO research and forecasts sometime in 2026. 

This equatorial surface-water cooling alters the exchange of heat and moisture between the ocean and atmosphere, reshaping global atmospheric circulation patterns. La Niña’s coupling with the ocean and atmosphere can shift mid-latitude jet streams, intensifying rainfall in some regions while bringing drought to others. Typically, La Niña years bring below-average rainfall to the American Southwest and above-average rainfall to the Northwest. But when the event is weak—whether El Niño or La Niña—the associated weather patterns can be 'notoriously difficult to predict,' said Josh Willis, an oceanographer and Sentinel-6 Michael Freilich project scientist at JPL in Southern California. 'It still has the potential to tilt our winter toward the dry side in the American Southwest, but it's never a guarantee, especially with a mild event like this one.`;

12: `New Timing for Stubble Burning in India - Every year for decades, long rivers of smoke and haze have spread across the Indo-Gangetic Plain in northern India from October to December. That's when farmers in Punjab, Haryana, Uttar Pradesh, Madhya Pradesh, and other states burn off plant 'stubble' after the rice harvest. When winds are weak and the atmosphere becomes stagnant, the haze can push levels of air pollution several times higher than limits recommended by the World Health Organization. Smoke typically mixes with particles and gases from other sources, such as industry, vehicles, domestic fires (heating and cooking), fireworks, and dust storms, to form the haze, though scientists consider stubble burning to be a major factor.  

In some ways, the seasonal timing of stubble fires in 2025 followed typical patterns. Air quality deteriorated in Delhi and several other cities for about a month after crop fires intensified during the last week of October, explained Hiren Jethva, a Morgan State University atmospheric scientist based at NASA’s Goddard Space Flight Center. For about a decade, Jethva has tracked the stubble burning season in India using satellites, and has made predictions about the intensity of the upcoming fire season based on vegetation observations.  

The MODIS (Moderate Resolution Imaging Spectroradiometer) on NASA's Aqua satellite captured this image of a smoky haze darkening skies over much of the plain on November 11, 2025. According to news reports, it was the first of several days in 2025 when pollution levels exceeded 400 on India's air quality index, the strongest rating on the scale. As in past years, the poor air quality prompted officials in some areas to close schools and institute more stringent air quality controls on construction.  

However, the daily timing of burning departs from what Jethva has seen in the past. He started tracking the number of fires years ago by primarily tallying observations from MODIS—which pass over locations on Earth each morning and afternoon on the Terra and Aqua satellites, respectively. Then, most fires were lit in the early afternoon between 1 p.m. and 2 p.m. local time.  

But in the past few years, stubble fires have occurred progressively later in the day, Jethva said. He identified the shift by analyzing observations from GEO-KOMPSAT-2A, a South Korean geostationary satellite launched in late 2018 that collects data every 10 minutes. Most stubble fires now happen between 4 p.m. and 6 p.m., meaning that fire-monitoring systems that rely solely on MODIS, or similar sensors like VIIRS (Visible Infrared Imaging Radiometer Suite), miss many of the fires. 'Farmers have changed their behavior,' he said.  

His analysis of GEO-KOMPSAT-2A observations indicates that the stubble burning activity in Punjab and Haryana was moderate in 2025 compared to other recent years. This year had higher numbers of fires compared to 2024, 2020, and 2019 but fewer fires than 2023, 2022, and 2021, he found. Indian Space Research Organization researchers have also pointed out the shift in the timing of stubble burning. In a Current Science study published in 2025, one group reported that MSG (Meteosat Second Generation) satellite observations showed a shift in peak fire activity from about 1:30 p.m. in 2020 to about 5:00 p.m. in 2024. In December 2025, researchers with the International Forum for Environment, Sustainability, & Technology (iForest) released a multi-satellite analysis that came to a similar conclusion.  

Meanwhile, parsing out precisely how much stubble fires contribute to poor air quality in Delhi compared to other sources of pollution remains a topic of active study and debate among scientists. 'Studies report contributions ranging from 10 to 50 percent,' said Pawan Gupta, a NASA research scientist who specializes in air quality. Gupta estimates that the stubble burning contribution ranges from 40 to 70 percent on a given day, dropping to 20 to 30 percent if averaged over a month or burning season, and under 10 percent if averaged annually. 'Meteorological conditions—like a shallow boundary layer height and low temperature—during the burning season add extra complexity,' he said.  

The timing of the fires may influence the degree to which stubble burning affects air quality. Some modeling research suggests that evening fires may lead to a stronger overnight buildup of particle pollution than early-afternoon fires because the planetary boundary layer, the lowest part of the atmosphere, tends to be shallower and have weaker winds at night, allowing pollutants to accumulate.`;


13: `Pacific Moisture Drenches the U.S. Northwest - Waves of heavy rainfall in early December 2025 spurred landslides and flooding in parts of the Pacific Northwest. The deluge was the result of a potent atmospheric river that took aim at the region starting around December 7. Atmospheric rivers are long, narrow bands of moisture that move like rivers in the sky, transporting water vapor from the tropics toward the poles. They occur around the planet, most often in autumn and winter, with the U.S. West Coast typically affected by moist air that originates near Hawaii. In this event, however, some of the moisture arrived from even farther away, originating roughly 7,000 miles (11,000 kilometers) across the Pacific from near the Philippines.  

This map shows the total precipitable water vapor in the atmosphere at 11:30 p.m. Pacific Time on December 10. It is derived from NASA’s GEOS (Goddard Earth Observing System) and uses satellite data and models of physical processes to approximate what is happening in the atmosphere. Precipitable water vapor represents the amount of water contained in a column of air, assuming all the water vapor condensed into liquid. The map’s green areas indicate the highest amounts of moisture. Note that not all precipitable water vapor falls as rain; at least some remains in the atmosphere. Nor is it a cap on how much rain can fall, since rainfall can increase as more moisture flows into a column of air. Still, it serves as a useful indicator of areas where excessive rainfall is likely.  

According to the National Weather Service, preliminary ground-based measurements showed that several locations in western Washington received more than 10 inches (250 millimeters) of rain over a 72-hour period ending on the morning of December 11. Seattle-Tacoma International Airport set a daily rainfall record on December 10, with 1.6 inches (40 millimeters). River flooding was ongoing on December 11, with the Skagit River and Snohomish River seeing record or near-record flood levels that day. Floodwater and mudslides have closed numerous roadways, including the eastbound lanes of I-90 out of western Washington.  

NASA’s Disasters Response Coordination System has been activated to support the ongoing response efforts by the Washington State Emergency Operations Center. The team will be posting maps and data products on its open-access mapping portal as new information becomes available.`;





};



function loadRandomQuiz() {
    descriptionElement.classList.add("hidden");

    let randomQuiz;
    do {
        randomQuiz = Math.floor(Math.random() * TOTAL_QUIZZES) + 1;
    } while (randomQuiz === currentQuiz);

    currentQuiz = randomQuiz;

    // Randomly choose between picX.jpg or picXa.jpg
    const imageVariant = Math.random() < 0.5 ? "" : "a";
    imageElement.src = `images/pic${currentQuiz}${imageVariant}.jpg`;

    descriptionElement.textContent = descriptions[currentQuiz];
}

revealBtn.addEventListener("click", () => {
    descriptionElement.classList.remove("hidden");
});

nextBtn.addEventListener("click", loadRandomQuiz);

// Load first quiz on page load
loadRandomQuiz();
